config/routes.rb
require 'resque/server'

LinkchatApp::Application.routes.draw do

  # iOS Application Redirect
  if ENV['IOS_DOWNLOAD_TRACKING_URL']
    get "/liable" => redirect(ENV['IOS_DOWNLOAD_TRACKING_URL'])
  end

  # Short Links
  get '/q/l' => 'short_links#latest_question', as: :short_latest_question

  get "/ie9proxy" => 'proxy#url'

  devise_for :users
  devise_scope :user do
    get 'campaign' => 'devise/registrations#new', as: :demo_registration
    get 'campaign_login' => 'devise/sessions#new', as: :demo_login
  end
  devise_for :partners
  devise_for :admin_users, ActiveAdmin::Devise.config

  get '/studio' => 'pages#studio' unless Rails.env.production?
  get '/welcome' => 'pages#welcome' unless Rails.env.production?
  get '/gallery' => 'pages#gallery' unless Rails.env.production?
  get '/rpush_check' => 'pages#rpush_check'

  ActiveAdmin.routes(self)

  root 'pages#welcome'
  get '/home' => 'pages#welcome', defaults: {new_web_app: true}
  get '/community(/:community_id)' => 'communities#join'
  get '/q/:uuid' => 'questions#new_response_from_uuid', as: :question_sharing
  get '/test' => 'pages#test' if Rails.env.development?
  get '/contests/exit' => 'contests#exit_contest', as: :exit_contest
  get '/contests/:uuid/sign_up' => 'contests#sign_up', as: :contest_sign_up
  post '/contests/new_user' => 'contests#new_user', as: :new_contest_user
  get '/gallery/:uuid' => 'contests#vote', as: :contest_vote
  get '/contests/:uuid/q/:quid' => 'contests#question', as: :contest_question
  post '/contests/:uuid/vote/:response_id' => 'contests#save_vote', as: :save_vote
  post '/contests/:uuid/scores' => 'contests#scores', as: :scores

  scope '/unit/:embeddable_unit_uuid', controller: 'embeddable_units' do
    get '/', action: 'start_survey', as: :embeddable_unit_start_survey
    get '/question/:question_id', action: :survey_question, as: :embeddable_unit_question
    post '/question/:question_id', action: :survey_response, as: :embeddable_unit_response
    get '/thank_you', action: :thank_you, as: :embeddable_unit_thank_you
    post '/quantcast', action: :quantcast, as: :embeddable_unit_quantcast
  end

  scope '/qp/:survey_uuid(/:unit_name)', controller: 'surveys' do
    get '/', action: 'start', as: :qp_start
    get '/q/:question_id', action: :question, as: :qp_question
    post '/q/:question_id', action: :create_response, as: :qp_create_response
    get '/thank_you', action: :thank_you, as: :qp_thank_you
    post '/quantcast', action: :quantcast, as: :qp_quantcast
    post '/q/:question_id/viewed', action: :question_viewed, as: :qp_question_viewed
  end

  resources :questions, shallow: true do
    get :preview, on: :member
    get :summary, on: :member
    get :share, on: :member
    get :results, on: :member
    post :update_targetable, on: :member
    get :skip, on: :member
    resources :responses
    resources :text_choice_responses
    resources :image_choice_responses
    resources :multiple_choice_responses
    resources :text_responses
    resources :order_responses
    resources :studio_responses
    resources :consumer_targets
    resources :enterprise_targets
  end

  resources :response_matchers, only: [:destroy]
  resources :text_response_matchers, only: [:destroy]
  resources :choice_response_matchers, only: [:destroy]
  resources :order_response_matchers, only: [:destroy]

  resources :inquiries
  resources :users do
    resources :surveys, only: [:destroy], param: :uuid
    resources :scenes, only: [:index, :new, :create]
    resources :studios, only: [:show]
    resources :segments do
      get :question_search, on: :member

      resources :response_matchers
      resources :text_response_matchers
      resources :choice_response_matchers
      resources :order_response_matchers
    end
    get :profile, on: :collection
    member do
      get :follow
      get :unfollow
      get :dashboard
      get :recent_responses
      get :recent_comments
      # get :campaigns
      get :publisher_question_packs
      get :publisher_dashboard
      get :new_campaign
      get :new_question
      get 'analytics/(:question_id)', to: 'users#analytics', as: :analytics
      get 'question_analytics/:question_id', to: 'users#question_analytics', as: :question_analytics
      get 'demographics/:question_id/(:choice_id)', to: 'users#demographics', as: :demographics
      get :question_search
      get :account
      get :avatar
      resources :listicles, param: :listicle_id do
        collection do
          post 'image_upload' => 'listicles#image_upload'
          get 'search' => 'listicles#search', as: :search
        end
        member do
          patch 'advanced_form' => 'advanced_listicles#update', as: :advanced_form
          get 'basic_form' => 'listicles#basic_form'
          get 'details' => 'listicles#details', as: :details
          resource :analytics, only: [:show], controller: :listicle_analytics, as: :listicle_analytics
          resources :questions, only: [:update, :edit], param: :question_id, controller: :listicle_questions, as: :listicle_questions
        end
      end
      get :behavioural_report, as: :behavioural_report
      get :cognitive_report, as: :cognitive_report
      resources :campaigns, param: :survey_id, only: [:index, :show]
      resources :image_search, only: [:create]
    end
  end

  post 'answer_listicle_question/:question_id' => 'listicles#answer_question', as: :answer_listicle_question
  get 'listicle/:id' => 'listicles#embed', as: :show_listicle
  post 'listicle/:id/quantcast' => 'listicles#quantcast', as: :listicle_quantcast

  resources :groups

  resources :group_members do
    delete '/' => 'group_members#destroy', on: :collection
  end

  resources :communities do
    get :invite, on: :member
  end

  resources :community_members do
    delete '/' => 'community_members#destroy', on: :collection
  end

  resources :question_types

  resources :yes_no_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :order_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :text_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :multiple_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :image_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :text_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :background_images
  resources :question_images
  resources :choice_images
  resources :order_choice_images


  mount TwoCents::API => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  authenticate :admin_user do
    mount Resque::Server.new, at: "/jobs"
  end

  # OmniAuth Callbacks
  constraints(provider: /#{Authentication::PROVIDERS.join('|')}/) do
    match '/auth/:provider/setup', to: 'omniauth#setup', via: [:get, :post]
    match '/auth/:provider/callback', to: 'omniauth#callback', via: [:get, :post]
    get '/auth/failure', to: 'omniauth#failure'
  end
end

app/models/community.rb
class Community < ActiveRecord::Base
  belongs_to :user, class_name: "Respondent"
  has_many :members, class_name: 'CommunityMember', dependent: :destroy
  has_many :member_users, through: :members, source: :user
  has_many :communities_targets
  has_many :consumer_targets, through: :communities_targets

  scope :trending_for_user, ->(user, page = 1, per_page = 20) {
    questions = Question.arel_table
    communities = arel_table
    communities_targets = Arel::Table.new(:communities_targets)
    targets = ConsumerTarget.arel_table
    membered_communities = CommunityMember.where(user_id: user.id).pluck(:community_id)

    # there we have public not empty communities(that have some questions in it), and on what user
    # is not subcribed. we set the limit and offset for records that will be returned
    not_empty_communities = communities.
        join(communities_targets).on(communities[:id].eq(communities_targets[:community_id])).
        join(targets).on(targets[:id].eq(communities_targets[:target_id])).
        join(questions).on(targets[:id].eq(questions[:target_id])).
        group(questions[:target_id]).having(questions[:id].count.gt(0))

    trending = not_empty_communities.
        where(communities[:id].not_in(membered_communities).and(communities[:private].eq(false))).
        take(per_page).skip((page - 1) * per_page).project(communities[Arel.star])

    find_by_sql(trending)
  }

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :user, presence: true
  validates :password, presence: true, if: :private?

  after_create :add_creator_as_member

  def public?
    !private?
  end

  private

  def add_creator_as_member
    member_users << user
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  skip_after_action :verify_authorized, only: [:join]

  def join
    # Redirect to the web app's community page
    path = "#/app/profile//communities/join"
    path += "?community_id=#{params[:community_id]}" if params[:community_id]
    redirect_to File.join(ENV['WEB_APP_URL'], path)
  end

  def create
    community = Community.new({ user: current_user }.merge(community_params))

    authorize community

    if community.save
      flash[:notice] = "Community \"#{community.name}\" was created."
    else
      flash[:alert] = community.errors.full_messages.join('; ')
    end

    redirect_to invite_community_path(community)
  end

  def destroy
    community = Community.find(params[:id])

    authorize community

    if community.destroy
      flash[:notice] = "Community \"#{community.name}\" was deleted."
    else
      flash[:alert] = community.errors.full_messages.join('; ')
    end

    redirect_to :back
  end

  def invite
    @community = Community.find(params.fetch(:id))

    authorize @community
  end

  private

  def community_params
    params.require(:community).permit(:name, :description, :private, :password)
  end
end

app/views/users/show/communities/_community.html.haml
%li
  .col-xs-5.info
    = community.name
    %br
    Members:
    = community.members.count
  .col-xs-4.controls
    = link_to 'javascript:void(0)' do
      %span.fa.fa-info-circle
    = link_to 'javascript:void(0)' do
      - if community.private?
        %span.fa.fa-lock
      - else
        %span.fa.fa-unlock-alt
  .col-xs-3.alt-controls
    - if community.member_users.include? current_user
      = link_to "Unsubscribe", "javascript:removeUserFromCommunity(#{current_user.id}, #{community.id})", class: 'btn btn-default'
    - else
      = link_to "Join", "javascript:addUserToCommunity(#{current_user.id}, #{community.id})", class: 'btn btn-default'
  .clearfix

app/views/users/show/communities/_create.html.haml
= form_for Community.new do |f|
  .row
    .col-xs-12
      = f.text_field :name, class: 'form-control',  placeholder: "Community Name..."
  %br
  .row
    .col-xs-6 Public or Private?
    .col-xs-6
      .btn-community{ data: { toggle: 'buttons' } }
        %label.btn.btn-primary.btn-sm.active
          = f.radio_button :private, false
          Public
        %label.btn.btn-primary.btn-sm
          = f.radio_button :private, true
          Private
  %br
  .row
    .col-xs-offset-6.col-xs-6
      = f.password_field :password, class: 'form-control', placeholder: "Community Password (if private)"
  %br
  .row
    .col-xs-12
      = f.text_area :description, class: 'form-control', placeholder: "Describe your community here..."
  %br
  .row
    .center
      = f.submit "Create community!", class: 'btn btn-primary'

app/views/users/show/communities/_join.html.haml
= form_tag user_path(@user), method: 'get' do
  = hidden_field_tag(:tab, 'communities')
  = hidden_field_tag(:subtab, 'join')
  = text_field_tag(:search_text, params[:search_text], placeholder: "Find communities to join...", class: 'form-control')

%br

%ul.items.communities-list
  = render partial: 'users/show/communities/community', collection: @communities

= form_for CommunityMember.new, html: { class: 'hidden' } do
  = hidden_field_tag :user_id
  = hidden_field_tag :community_id
  = submit_tag
= form_for :community_member, url: community_members_path, method: :delete, html: { id: 'destroy_community_member', class: 'hidden' } do
  = hidden_field_tag :user_id
  = hidden_field_tag :community_id
  = submit_tag

app/views/users/show/communities/_my.html.haml
%h3 Communities I am a member of
%ul.items.communities-list
  - if @member_communities.empty?
    %h4 There are no member communities.
  = render partial: 'users/show/communities/community', collection: @member_communities

%h3 Communities I manage
- if @user == current_user
  .center
    = link_to "Create a community", user_path(tab: 'communities', subtab: 'create'), class: 'btn btn-default'
%ul.items.communities-list
  - if @communities.empty?
    %h4 There are no managing communities.
  = render partial: 'users/show/communities/my_community', collection: @communities

app/views/users/show/communities/_my_community.html.haml
%li
  .col-xs-5.info
    = my_community.name
    %br
    Members:
    = my_community.members.count
  .col-xs-offset-4.col-xs-3.alt-controls
    - if my_community.member_users.include? current_user
      = link_to "Delete", my_community, method: :delete, class: 'btn btn-primary'
  .col-xs-9.controls
    = link_to 'javascript:void(0)' do
      %span.fa.fa-info-circle
  .col-xs-3
    = link_to 'javascript:void(0)', class: 'btn btn-default btn-xs' do
      Invite people to
      %br
      this community
  .clearfix