config/routes.rb
require 'resque/server'

LinkchatApp::Application.routes.draw do

  # iOS Application Redirect
  if ENV['IOS_DOWNLOAD_TRACKING_URL']
    get "/liable" => redirect(ENV['IOS_DOWNLOAD_TRACKING_URL'])
  end

  # Short Links
  get '/q/l' => 'short_links#latest_question', as: :short_latest_question

  get "/ie9proxy" => 'proxy#url'

  devise_for :users
  devise_scope :user do
    get 'campaign' => 'devise/registrations#new', as: :demo_registration
    get 'campaign_login' => 'devise/sessions#new', as: :demo_login
  end
  devise_for :partners
  devise_for :admin_users, ActiveAdmin::Devise.config

  get '/studio' => 'pages#studio' unless Rails.env.production?
  get '/welcome' => 'pages#welcome' unless Rails.env.production?
  get '/gallery' => 'pages#gallery' unless Rails.env.production?
  get '/rpush_check' => 'pages#rpush_check'

  ActiveAdmin.routes(self)

  root 'pages#welcome'
  get '/home' => 'pages#welcome', defaults: {new_web_app: true}
  get '/community(/:community_id)' => 'communities#join'
  get '/q/:uuid' => 'questions#new_response_from_uuid', as: :question_sharing
  get '/test' => 'pages#test' if Rails.env.development?
  get '/contests/exit' => 'contests#exit_contest', as: :exit_contest
  get '/contests/:uuid/sign_up' => 'contests#sign_up', as: :contest_sign_up
  post '/contests/new_user' => 'contests#new_user', as: :new_contest_user
  get '/gallery/:uuid' => 'contests#vote', as: :contest_vote
  get '/contests/:uuid/q/:quid' => 'contests#question', as: :contest_question
  post '/contests/:uuid/vote/:response_id' => 'contests#save_vote', as: :save_vote
  post '/contests/:uuid/scores' => 'contests#scores', as: :scores

  scope '/unit/:embeddable_unit_uuid', controller: 'embeddable_units' do
    get '/', action: 'start_survey', as: :embeddable_unit_start_survey
    get '/question/:question_id', action: :survey_question, as: :embeddable_unit_question
    post '/question/:question_id', action: :survey_response, as: :embeddable_unit_response
    get '/thank_you', action: :thank_you, as: :embeddable_unit_thank_you
    post '/quantcast', action: :quantcast, as: :embeddable_unit_quantcast
  end

  scope '/qp/:survey_uuid(/:unit_name)', controller: 'surveys' do
    get '/', action: 'start', as: :qp_start
    get '/q/:question_id', action: :question, as: :qp_question
    post '/q/:question_id', action: :create_response, as: :qp_create_response
    get '/thank_you', action: :thank_you, as: :qp_thank_you
    post '/quantcast', action: :quantcast, as: :qp_quantcast
    post '/q/:question_id/viewed', action: :question_viewed, as: :qp_question_viewed
  end

  resources :questions, shallow: true do
    get :preview, on: :member
    get :summary, on: :member
    get :share, on: :member
    get :results, on: :member
    post :update_targetable, on: :member
    get :skip, on: :member
    resources :responses
    resources :text_choice_responses
    resources :image_choice_responses
    resources :multiple_choice_responses
    resources :text_responses
    resources :order_responses
    resources :studio_responses
    resources :consumer_targets
    resources :enterprise_targets
  end

  resources :response_matchers, only: [:destroy]
  resources :text_response_matchers, only: [:destroy]
  resources :choice_response_matchers, only: [:destroy]
  resources :order_response_matchers, only: [:destroy]

  resources :inquiries
  resources :users do
    resources :surveys, only: [:destroy], param: :uuid
    resources :scenes, only: [:index, :new, :create]
    resources :studios, only: [:show]
    resources :segments do
      get :question_search, on: :member

      resources :response_matchers
      resources :text_response_matchers
      resources :choice_response_matchers
      resources :order_response_matchers
    end
    get :profile, on: :collection
    member do
      get :follow
      get :unfollow
      get :dashboard
      get :recent_responses
      get :recent_comments
      # get :campaigns
      get :publisher_question_packs
      get :publisher_dashboard
      get :new_campaign
      get :new_question
      get 'analytics/(:question_id)', to: 'users#analytics', as: :analytics
      get 'question_analytics/:question_id', to: 'users#question_analytics', as: :question_analytics
      get 'demographics/:question_id/(:choice_id)', to: 'users#demographics', as: :demographics
      get :question_search
      get :account
      get :avatar
      resources :listicles, param: :listicle_id do
        collection do
          post 'image_upload' => 'listicles#image_upload'
          get 'search' => 'listicles#search', as: :search
        end
        member do
          patch 'advanced_form' => 'advanced_listicles#update', as: :advanced_form
          get 'basic_form' => 'listicles#basic_form'
          get 'details' => 'listicles#details', as: :details
          resource :analytics, only: [:show], controller: :listicle_analytics, as: :listicle_analytics
          resources :questions, only: [:update, :edit], param: :question_id, controller: :listicle_questions, as: :listicle_questions
        end
      end
      get :behavioural_report, as: :behavioural_report
      get :cognitive_report, as: :cognitive_report
      resources :campaigns, param: :survey_id, only: [:index, :show]
      resources :image_search, only: [:create]
    end
  end

  post 'answer_listicle_question/:question_id' => 'listicles#answer_question', as: :answer_listicle_question
  get 'listicle/:id' => 'listicles#embed', as: :show_listicle
  post 'listicle/:id/quantcast' => 'listicles#quantcast', as: :listicle_quantcast

  resources :groups

  resources :group_members do
    delete '/' => 'group_members#destroy', on: :collection
  end

  resources :communities do
    get :invite, on: :member
  end

  resources :community_members do
    delete '/' => 'community_members#destroy', on: :collection
  end

  resources :question_types

  resources :yes_no_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :order_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :text_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :multiple_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :image_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :text_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :background_images
  resources :question_images
  resources :choice_images
  resources :order_choice_images


  mount TwoCents::API => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  authenticate :admin_user do
    mount Resque::Server.new, at: "/jobs"
  end

  # OmniAuth Callbacks
  constraints(provider: /#{Authentication::PROVIDERS.join('|')}/) do
    match '/auth/:provider/setup', to: 'omniauth#setup', via: [:get, :post]
    match '/auth/:provider/callback', to: 'omniauth#callback', via: [:get, :post]
    get '/auth/failure', to: 'omniauth#failure'
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  layout "surveys"

  skip_before_action :authenticate_user!, :find_recent_questions

  before_action :set_expiration_headers, only: [:start]
  before_action :migrate_user_cookie, except: [:question_viewed, :destroy]
  before_action :preload_and_authorize, except: [:destroy]
  after_action :allow_iframe, except: [:question_viewed, :destroy]

  protect_from_forgery with: :null_session

  helper_method \
    :settings,
    :previous_question_path,
    :next_question_path,
    :cookie_user,
    :current_ad_unit_user,
    :question_class,
    :meta_data_for

  rescue_from(Pundit::NotAuthorizedError) do
    render :invalid_survey
  end

  rescue_from(ActiveRecord::RecordNotFound) { render :invalid_survey }

  rescue_from(ActiveRecord::ActiveRecordError) do |ex|
    Airbrake.notify_or_ignore(ex)
    render :invalid_survey, layout: false
  end

  def destroy
    @survey = current_user.surveys.find_by(uuid: params[:uuid])
    skip_authorization
    @survey.destroy
    redirect_to campaigns_path(current_user)
  end

  def question_viewed
    question = question_scope.find(params[:question_id])
    question.try :viewed!
    render text: "OK #{question.try :id}"
  end

  def start
    @original_referrer = @referrer = request.referrer
    # session[:survey_original_referrer] = @original_referrer
    @thank_you_html = survey.parsed_thank_you_html(request.query_parameters).html_safe || default_thank_you
    @question = question_scope.first
  end

  def create_response
    @question = question_scope.find(params[:question_id])

    @response = @question.responses.create!(response_params.merge(source: 'embeddable')) do |r|
      r.user = current_ad_unit_user
    end
    @original_referrer = @response.original_referrer

    # Whenever they answer the first question, reset the responses so they can answer them all again
    # We can't do this in start since it may be cached on cloudfront
    reset_session_responses if @question == question_scope.first

    # Remember that they answered this question so we show summary data if the hit the back button
    remember_session_response @response

    render :question
  end

  def question
    @question = question_scope.find(params[:question_id])

    # Find the response if they responded in this session (since the last time they started)
    @response = session_response_for_question @question
    @original_referrer = params[:original_referrer]
    # @original_referrer = session[:survey_original_referrer]
  end

  def thank_you
    @referrer = params[:original_referrer]
    # @referrer = session[:survey_original_referrer]
    @sample_surveys = sample_surveys
    reset_session_responses
    render :thank_you, layout: false
  end

  def quantcast
    DataProvider.where(name: 'quantcast').first_or_create
    demographic = current_ad_unit_user.demographics.quantcast.first_or_create
    demographic.ip_address = request.remote_ip
    demographic.user_agent = request.env['HTTP_USER_AGENT']
    demographic.update_from_provider_data!('quantcast', '1.0', quantcast_data)
    head :ok
  end

  def default_thank_you
    @referrer = params[:original_referrer]
    # @referrer = session[:survey_original_referrer]
    @sample_surveys = sample_surveys
    render_to_string partial: 'surveys/default_thank_you'
  end

  private

    def sample_surveys
      SampleSurveySearcher.new(current_user, @survey, @referrer || request.referrer || '',
                               @ad_unit.related_surveys_count).sample_surveys
    end

    def settings
      @survey_settings ||= Setting.fetch_values(
        'ad_unit_expires',
        'ad_cache_control',
        'embeddable_unit_cta_min_start',
        'embeddable_unit_cta_max_start',
        'embeddable_unit_cta_fade_speed',
        'embeddable_unit_cta_duration',
        'embeddable_unit_cta_repeat',
        'embeddable_unit_feedback_duration',
        'embeddable_unit_vote_text',
        'embeddable_unit_vote_bounce_speed'
      )
    end

    def set_expiration_headers
      if settings[:ad_unit_expires]
        headers["Expires"] = settings[:ad_unit_expires]
      end

      if settings[:ad_cache_control]
        headers["Cache-Control"] = settings[:ad_cache_control]
      end
    end

    def quantcast_data
      params[:quantcast]
    end

    def question_scope
      survey.questions.eager_load(:background_image, :choices)
    end

    def survey
      @survey ||= Survey.eager_load(questions_surveys: [:question])
        .order('questions_surveys.position ASC')
        .find_by!(uuid: params[:survey_uuid])
    end

    def ad_unit
      @ad_unit ||= begin
        ad_unit_name = params[:unit_name] || AdUnit::DEFAULT_NAME
        AdUnit.find_by!(name: ad_unit_name)
      end
    end

    def preload_and_authorize
      survey
      ad_unit
      authorize survey
    end

    def response_params
      # Using 'response' as the base param with all the parts allowed for various response types
      # Relying on response validation to sort out bad params
      params.require(:response).permit(:choice_id, :text, :original_referrer, choice_ids: [])
    end

    def question_class
      classes = if @question.try(:min_responses).to_i > 1
        ['MultipleChoiceQuestion']
      else
        [@question.try(:class).try(:name)]
      end

      classes.push "choices-#{@question.try(:choices).try(:length)}"
      classes.push('has-response') if @response
      classes.join(' ')
    end

    def migrate_user_cookie
      # Migrate old cookie from statisfy subdomain to base domain
      if Rails.env.production? && ((_user = cookies.signed[:eu_user]))
        cookies.delete(:eu_user, domain: request.host)
        store_eu_user(_user)
      end
    end

    def cookie_user
      @cookie_user ||= if cookies.signed["eu_user_#{Rails.env}"]
        Respondent.find_by(id: cookies.signed["eu_user_#{Rails.env}"])
      end
    end

    def store_eu_user(user_id)
      cookies.permanent.signed["eu_user_#{Rails.env}"] = {
        value: user_id,
        domain: request.host.split('.').last(2).join('.')
      }
    end

    def current_ad_unit_user
      @ad_unit_user ||= begin
        ad_unit_user = cookie_user || Anonymous.create!(auto_feed: false)
        store_eu_user(ad_unit_user.id)
        ad_unit_user
      end
    end

    def previous_question_path(question, original_referrer)
      @prev_question = if prev_question = survey.previous_question(question)
        qp_question_path(survey.uuid, ad_unit.name, prev_question.id, original_referrer: original_referrer)
      end
    end

    def next_question_path(question, original_referrer)
      @next_question = if next_question = survey.next_question(question)
        qp_question_path(survey.uuid, @ad_unit.name, next_question.id, original_referrer: original_referrer)
      else
        qp_thank_you_path(survey.uuid, @ad_unit.name, original_referrer: original_referrer)
      end
    end

    ##
    ## Helpers for storing and retrieving responses during one survey session
    ##

    def reset_session_responses
      session[:survey_response_ids] = {}
    end

    def session_response_for_question question
      session[:survey_response_ids] ||= {}
      response_id = session[:survey_response_ids][question.id]
      question.responses.where(user_id: current_ad_unit_user.id).find_by(id: response_id) if response_id
    end

    def remember_session_response response
      session[:survey_response_ids] ||= {}
      session[:survey_response_ids][response.question.id] = response.id
    end

    ##
    ## Helpers for storing and retrieving query params
    ##

    def meta_data_for(image)
      {
        id: image.id,
        url: image.web_image_url,
        meta: image.ad_unit_info(@ad_unit.name).try(:meta_data)
      }.to_json
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def responding?
    params[:action] == 'create_response'
  end
end

app/views/surveys/responsive_rectangle/_image_choice_question.html.haml
= render partial: 'surveys/responsive_rectangle/vote'
- content_for :between_buttons do
  - question.ordered_choices_for(cookie_user).each_with_index do |c, i|
    - meta = meta_data_for(c.background_image)
    - if answer
      %div{class: "image-choice index-#{i}", data: {image: meta}}
        - ratio = (c.response_ratio * 100).to_i
        .is-selected
          %i.fa.fa-check.color1
        %div.bar-blue.color1-bg{data: {response: ratio}}
          .bar-graph.color2-bg
          .bar-selected
          .bar-response

        .spacer
        .text.tooltip{title: c.title}= c.title

    - else
      - url = qp_create_response_url(@survey.uuid, @ad_unit.name, question)
      = button_to url, form: {target: '_self', data: {image: meta}, class: "image-choice index-#{i}"},
        params: {'response[choice_id]' => c.id, 'response[original_referrer]' => original_referrer},
        'data-targeting-script' => c.targeting_script do
        .is-selected
          %i.fa.fa-check.color1
        .overlay
        .spacer
        .text.tooltip{title: c.title}= c.title
  = render partial: 'surveys/single_choice_targeting_script'

app/views/surveys/responsive_rectangle/_multiple_choice_question.html.haml
= render partial: 'surveys/responsive_rectangle/vote'
- content_for :between_buttons do
  - question.ordered_choices_for(cookie_user).each_with_index do |c, i|
    %div{class: "image-choice index-#{i}", data: {index: i, choice_id: c.id, image: meta_data_for(c.background_image),
    'targeting-script' => c.targeting_script}}
      .is-selected
        %i.fa.fa-check.color1
      - if !answer
        .overlay
      - else
        - ratio = (c.response_ratio * 100).to_i
        %div.bar-blue.color1-bg{data: {response: ratio}}
          .bar-graph.color2-bg
          .bar-selected
          .bar-response
      .spacer
      .text.tooltip{title: c.title}= c.title

- unless answer
  - content_for :below_buttons do
    - url = qp_create_response_url(@survey.uuid, @ad_unit.name, question)
    = form_tag url, target: '_self', id: 'multiple-choice-form', data: {min: question.min_responses, max: question.max_responses} do
      = hidden_field_tag 'response[original_referrer]', original_referrer
      .bar.color1-bg
        %button#multiple-choice-submit{type:'submit'}= 'Submit'
  = render partial: 'surveys/multiple_choice_targeting_script'

app/views/surveys/responsive_rectangle/_order_question.html.haml
= render partial: 'surveys/responsive_rectangle/vote'
- content_for :between_buttons do
  #order-choice-sort
    - if answer
      - choices = answer.choices
    - else
      - choices = question.ordered_choices_for(cookie_user)

    - choices.each_with_index do |c, i|
      .order-choice-bar{data: {choice_id: c.id, image: meta_data_for(c.background_image),
      'targeting-script' => c.targeting_script}}
        .order-choice-title.tooltip{title: c.title}= c.title
        - if answer
          - ratio = (c.response_ratio * 100).to_i
          .bar-blue.color1-bg{data: {response: ratio}}
            .bar-graph.color2-bg
            .bar-selected
            .bar-response
        - else
          %div{style: 'position: relative'}
            .overlay
            .order-choice-orderer
              = image_tag 'ad_units/prioritizer.png'


- unless answer.present?
  - content_for :below_buttons do
    - url = qp_create_response_url(@survey.uuid, @ad_unit.name, question)
    = form_tag url, target: '_self' do
      = hidden_field_tag 'response[original_referrer]', original_referrer
      - question.choices.each_with_index do |c, i|
        = hidden_field_tag 'response[choice_ids][]', c.id, id: "index-#{i}"

      .bar.color1-bg
        %button#order-choice-submit{type:'submit'}= 'Submit'
  = render partial: 'surveys/order_choice_targeting_script'

app/views/surveys/responsive_rectangle/_text_choice_question.html.haml
= render partial: 'surveys/responsive_rectangle/vote'
- content_for :between_buttons do
  .main-image{data: {image: meta_data_for(question.background_image)}}
- content_for :below_buttons do
  - question.ordered_choices_for(cookie_user).each do |c|
    - if answer.present?
      - ratio = (c.response_ratio * 100).to_i
      %div.bar.color1-bg{data: {response: ratio}}
        .bar-graph.color2-bg
        .bar-selected
        .bar-response
        .bar-title.tooltip{title: c.title}= c.title
    - else
      - url = qp_create_response_url(@survey.uuid, @ad_unit.name, @question)
      = button_to url, form: {target: '_self', class: 'bar-blue color1-bg'},
        params: {'response[choice_id]' => c.id, 'response[original_referrer]' => original_referrer},
        'data-targeting-script' => c.targeting_script do
        .is-selected
          %i.fa.fa-check.color1
        .bar-title.tooltip{title: c.title}= c.title
        .bar-overlay.overlay
  = render partial: 'surveys/single_choice_targeting_script'

app/views/surveys/responsive_rectangle/_text_question.html.haml
= render partial: 'surveys/responsive_rectangle/vote'
- meta = meta_data_for(question.background_image)

- content_for :between_buttons do
  .main-image{data: {image: meta}}

- content_for :below_buttons do
  - if answer.present?
    #answered-count.bar.color1-bg
      .bar-title= t('embeddable_unit.response_count', count: question.responses.size)
    %a.bar-orange.color1-bg{href: question_sharing_url(uuid: question.id, subdomain: 'a')}
      .bar-title= t('embeddable_unit.see_responses')
  - else
    - url = qp_create_response_url(@survey.uuid, @ad_unit.name, question)
    = form_tag url, target: '_self' do
      = hidden_field_tag 'response[original_referrer]', original_referrer
      .textarea.color1-bg
        = text_area_tag 'response[text]', nil, placeholder: 'Type your answer here', style: "border-color: #{@survey.theme.color1}"
      .bar.color1-bg
        %button{type:'submit'}= 'Submit'
  :javascript
    $('button[type="submit"]').on('click', function(e) {
      e.preventDefault();
      var text = $('#response_text').val();
      if (!text.length) {
        alert('Your response cannot be empty, please write something');
      } else {
        $('form').submit();
      }
    });

app/views/surveys/responsive_rectangle/_vote.html.haml
- content_for :top_content do
  #vote-block
    #vote-tooltip
      Vote here!

app/views/surveys/responsive_rectangle/_yes_no_question.html.haml
= render "surveys/response_fields/text_choice_question", answer: answer, question: question, original_referrer: original_referrer