config/routes.rb
require 'resque/server'

LinkchatApp::Application.routes.draw do

  # iOS Application Redirect
  if ENV['IOS_DOWNLOAD_TRACKING_URL']
    get "/liable" => redirect(ENV['IOS_DOWNLOAD_TRACKING_URL'])
  end

  # Short Links
  get '/q/l' => 'short_links#latest_question', as: :short_latest_question

  get "/ie9proxy" => 'proxy#url'

  devise_for :users
  devise_scope :user do
    get 'campaign' => 'devise/registrations#new', as: :demo_registration
    get 'campaign_login' => 'devise/sessions#new', as: :demo_login
  end
  devise_for :partners
  devise_for :admin_users, ActiveAdmin::Devise.config

  get '/studio' => 'pages#studio' unless Rails.env.production?
  get '/welcome' => 'pages#welcome' unless Rails.env.production?
  get '/gallery' => 'pages#gallery' unless Rails.env.production?
  get '/rpush_check' => 'pages#rpush_check'

  ActiveAdmin.routes(self)

  root 'pages#welcome'
  get '/home' => 'pages#welcome', defaults: {new_web_app: true}
  get '/community(/:community_id)' => 'communities#join'
  get '/q/:uuid' => 'questions#new_response_from_uuid', as: :question_sharing
  get '/test' => 'pages#test' if Rails.env.development?
  get '/contests/exit' => 'contests#exit_contest', as: :exit_contest
  get '/contests/:uuid/sign_up' => 'contests#sign_up', as: :contest_sign_up
  post '/contests/new_user' => 'contests#new_user', as: :new_contest_user
  get '/gallery/:uuid' => 'contests#vote', as: :contest_vote
  get '/contests/:uuid/q/:quid' => 'contests#question', as: :contest_question
  post '/contests/:uuid/vote/:response_id' => 'contests#save_vote', as: :save_vote
  post '/contests/:uuid/scores' => 'contests#scores', as: :scores

  scope '/unit/:embeddable_unit_uuid', controller: 'embeddable_units' do
    get '/', action: 'start_survey', as: :embeddable_unit_start_survey
    get '/question/:question_id', action: :survey_question, as: :embeddable_unit_question
    post '/question/:question_id', action: :survey_response, as: :embeddable_unit_response
    get '/thank_you', action: :thank_you, as: :embeddable_unit_thank_you
    post '/quantcast', action: :quantcast, as: :embeddable_unit_quantcast
  end

  scope '/qp/:survey_uuid(/:unit_name)', controller: 'surveys' do
    get '/', action: 'start', as: :qp_start
    get '/q/:question_id', action: :question, as: :qp_question
    post '/q/:question_id', action: :create_response, as: :qp_create_response
    get '/thank_you', action: :thank_you, as: :qp_thank_you
    post '/quantcast', action: :quantcast, as: :qp_quantcast
    post '/q/:question_id/viewed', action: :question_viewed, as: :qp_question_viewed
  end

  resources :questions, shallow: true do
    get :preview, on: :member
    get :summary, on: :member
    get :share, on: :member
    get :results, on: :member
    post :update_targetable, on: :member
    get :skip, on: :member
    resources :responses
    resources :text_choice_responses
    resources :image_choice_responses
    resources :multiple_choice_responses
    resources :text_responses
    resources :order_responses
    resources :studio_responses
    resources :consumer_targets
    resources :enterprise_targets
  end

  resources :response_matchers, only: [:destroy]
  resources :text_response_matchers, only: [:destroy]
  resources :choice_response_matchers, only: [:destroy]
  resources :order_response_matchers, only: [:destroy]

  resources :inquiries
  resources :users do
    resources :surveys, only: [:destroy], param: :uuid
    resources :scenes, only: [:index, :new, :create]
    resources :studios, only: [:show]
    resources :segments do
      get :question_search, on: :member

      resources :response_matchers
      resources :text_response_matchers
      resources :choice_response_matchers
      resources :order_response_matchers
    end
    get :profile, on: :collection
    member do
      get :follow
      get :unfollow
      get :dashboard
      get :recent_responses
      get :recent_comments
      # get :campaigns
      get :publisher_question_packs
      get :publisher_dashboard
      get :new_campaign
      get :new_question
      get 'analytics/(:question_id)', to: 'users#analytics', as: :analytics
      get 'question_analytics/:question_id', to: 'users#question_analytics', as: :question_analytics
      get 'demographics/:question_id/(:choice_id)', to: 'users#demographics', as: :demographics
      get :question_search
      get :account
      get :avatar
      resources :listicles, param: :listicle_id do
        collection do
          post 'image_upload' => 'listicles#image_upload'
          get 'search' => 'listicles#search', as: :search
        end
        member do
          patch 'advanced_form' => 'advanced_listicles#update', as: :advanced_form
          get 'basic_form' => 'listicles#basic_form'
          get 'details' => 'listicles#details', as: :details
          resource :analytics, only: [:show], controller: :listicle_analytics, as: :listicle_analytics
          resources :questions, only: [:update, :edit], param: :question_id, controller: :listicle_questions, as: :listicle_questions
        end
      end
      get :behavioural_report, as: :behavioural_report
      get :cognitive_report, as: :cognitive_report
      resources :campaigns, param: :survey_id, only: [:index, :show]
      resources :image_search, only: [:create]
    end
  end

  post 'answer_listicle_question/:question_id' => 'listicles#answer_question', as: :answer_listicle_question
  get 'listicle/:id' => 'listicles#embed', as: :show_listicle
  post 'listicle/:id/quantcast' => 'listicles#quantcast', as: :listicle_quantcast

  resources :groups

  resources :group_members do
    delete '/' => 'group_members#destroy', on: :collection
  end

  resources :communities do
    get :invite, on: :member
  end

  resources :community_members do
    delete '/' => 'community_members#destroy', on: :collection
  end

  resources :question_types

  resources :yes_no_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :order_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :text_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :multiple_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :image_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :text_choice_questions do
    get :target, on: :member
    post :enable, on: :member
    resources :comments, only: :create
  end

  resources :background_images
  resources :question_images
  resources :choice_images
  resources :order_choice_images


  mount TwoCents::API => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  authenticate :admin_user do
    mount Resque::Server.new, at: "/jobs"
  end

  # OmniAuth Callbacks
  constraints(provider: /#{Authentication::PROVIDERS.join('|')}/) do
    match '/auth/:provider/setup', to: 'omniauth#setup', via: [:get, :post]
    match '/auth/:provider/callback', to: 'omniauth#callback', via: [:get, :post]
    get '/auth/failure', to: 'omniauth#failure'
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  layout "surveys"

  skip_before_action :authenticate_user!, :find_recent_questions

  before_action :set_expiration_headers, only: [:start]
  before_action :migrate_user_cookie, except: [:question_viewed, :destroy]
  before_action :preload_and_authorize, except: [:destroy]
  after_action :allow_iframe, except: [:question_viewed, :destroy]

  protect_from_forgery with: :null_session

  helper_method \
    :settings,
    :previous_question_path,
    :next_question_path,
    :cookie_user,
    :current_ad_unit_user,
    :question_class,
    :meta_data_for

  rescue_from(Pundit::NotAuthorizedError) do
    render :invalid_survey
  end

  rescue_from(ActiveRecord::RecordNotFound) { render :invalid_survey }

  rescue_from(ActiveRecord::ActiveRecordError) do |ex|
    Airbrake.notify_or_ignore(ex)
    render :invalid_survey, layout: false
  end

  def destroy
    @survey = current_user.surveys.find_by(uuid: params[:uuid])
    skip_authorization
    @survey.destroy
    redirect_to campaigns_path(current_user)
  end

  def question_viewed
    question = question_scope.find(params[:question_id])
    question.try :viewed!
    render text: "OK #{question.try :id}"
  end

  def start
    @original_referrer = @referrer = request.referrer
    # session[:survey_original_referrer] = @original_referrer
    @thank_you_html = survey.parsed_thank_you_html(request.query_parameters).html_safe || default_thank_you
    @question = question_scope.first
  end

  def create_response
    @question = question_scope.find(params[:question_id])

    @response = @question.responses.create!(response_params.merge(source: 'embeddable')) do |r|
      r.user = current_ad_unit_user
    end
    @original_referrer = @response.original_referrer

    # Whenever they answer the first question, reset the responses so they can answer them all again
    # We can't do this in start since it may be cached on cloudfront
    reset_session_responses if @question == question_scope.first

    # Remember that they answered this question so we show summary data if the hit the back button
    remember_session_response @response

    render :question
  end

  def question
    @question = question_scope.find(params[:question_id])

    # Find the response if they responded in this session (since the last time they started)
    @response = session_response_for_question @question
    @original_referrer = params[:original_referrer]
    # @original_referrer = session[:survey_original_referrer]
  end

  def thank_you
    @referrer = params[:original_referrer]
    # @referrer = session[:survey_original_referrer]
    @sample_surveys = sample_surveys
    reset_session_responses
    render :thank_you, layout: false
  end

  def quantcast
    DataProvider.where(name: 'quantcast').first_or_create
    demographic = current_ad_unit_user.demographics.quantcast.first_or_create
    demographic.ip_address = request.remote_ip
    demographic.user_agent = request.env['HTTP_USER_AGENT']
    demographic.update_from_provider_data!('quantcast', '1.0', quantcast_data)
    head :ok
  end

  def default_thank_you
    @referrer = params[:original_referrer]
    # @referrer = session[:survey_original_referrer]
    @sample_surveys = sample_surveys
    render_to_string partial: 'surveys/default_thank_you'
  end

  private

    def sample_surveys
      SampleSurveySearcher.new(current_user, @survey, @referrer || request.referrer || '',
                               @ad_unit.related_surveys_count).sample_surveys
    end

    def settings
      @survey_settings ||= Setting.fetch_values(
        'ad_unit_expires',
        'ad_cache_control',
        'embeddable_unit_cta_min_start',
        'embeddable_unit_cta_max_start',
        'embeddable_unit_cta_fade_speed',
        'embeddable_unit_cta_duration',
        'embeddable_unit_cta_repeat',
        'embeddable_unit_feedback_duration',
        'embeddable_unit_vote_text',
        'embeddable_unit_vote_bounce_speed'
      )
    end

    def set_expiration_headers
      if settings[:ad_unit_expires]
        headers["Expires"] = settings[:ad_unit_expires]
      end

      if settings[:ad_cache_control]
        headers["Cache-Control"] = settings[:ad_cache_control]
      end
    end

    def quantcast_data
      params[:quantcast]
    end

    def question_scope
      survey.questions.eager_load(:background_image, :choices)
    end

    def survey
      @survey ||= Survey.eager_load(questions_surveys: [:question])
        .order('questions_surveys.position ASC')
        .find_by!(uuid: params[:survey_uuid])
    end

    def ad_unit
      @ad_unit ||= begin
        ad_unit_name = params[:unit_name] || AdUnit::DEFAULT_NAME
        AdUnit.find_by!(name: ad_unit_name)
      end
    end

    def preload_and_authorize
      survey
      ad_unit
      authorize survey
    end

    def response_params
      # Using 'response' as the base param with all the parts allowed for various response types
      # Relying on response validation to sort out bad params
      params.require(:response).permit(:choice_id, :text, :original_referrer, choice_ids: [])
    end

    def question_class
      classes = if @question.try(:min_responses).to_i > 1
        ['MultipleChoiceQuestion']
      else
        [@question.try(:class).try(:name)]
      end

      classes.push "choices-#{@question.try(:choices).try(:length)}"
      classes.push('has-response') if @response
      classes.join(' ')
    end

    def migrate_user_cookie
      # Migrate old cookie from statisfy subdomain to base domain
      if Rails.env.production? && ((_user = cookies.signed[:eu_user]))
        cookies.delete(:eu_user, domain: request.host)
        store_eu_user(_user)
      end
    end

    def cookie_user
      @cookie_user ||= if cookies.signed["eu_user_#{Rails.env}"]
        Respondent.find_by(id: cookies.signed["eu_user_#{Rails.env}"])
      end
    end

    def store_eu_user(user_id)
      cookies.permanent.signed["eu_user_#{Rails.env}"] = {
        value: user_id,
        domain: request.host.split('.').last(2).join('.')
      }
    end

    def current_ad_unit_user
      @ad_unit_user ||= begin
        ad_unit_user = cookie_user || Anonymous.create!(auto_feed: false)
        store_eu_user(ad_unit_user.id)
        ad_unit_user
      end
    end

    def previous_question_path(question, original_referrer)
      @prev_question = if prev_question = survey.previous_question(question)
        qp_question_path(survey.uuid, ad_unit.name, prev_question.id, original_referrer: original_referrer)
      end
    end

    def next_question_path(question, original_referrer)
      @next_question = if next_question = survey.next_question(question)
        qp_question_path(survey.uuid, @ad_unit.name, next_question.id, original_referrer: original_referrer)
      else
        qp_thank_you_path(survey.uuid, @ad_unit.name, original_referrer: original_referrer)
      end
    end

    ##
    ## Helpers for storing and retrieving responses during one survey session
    ##

    def reset_session_responses
      session[:survey_response_ids] = {}
    end

    def session_response_for_question question
      session[:survey_response_ids] ||= {}
      response_id = session[:survey_response_ids][question.id]
      question.responses.where(user_id: current_ad_unit_user.id).find_by(id: response_id) if response_id
    end

    def remember_session_response response
      session[:survey_response_ids] ||= {}
      session[:survey_response_ids][response.question.id] = response.id
    end

    ##
    ## Helpers for storing and retrieving query params
    ##

    def meta_data_for(image)
      {
        id: image.id,
        url: image.web_image_url,
        meta: image.ad_unit_info(@ad_unit.name).try(:meta_data)
      }.to_json
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def responding?
    params[:action] == 'create_response'
  end
end

app/views/surveys/_analytics.html.haml
- if ENV['GOOGLE_ANALYTICS_ID'].present?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{ENV['GOOGLE_ANALYTICS_ID']}', 'auto');

app/views/surveys/_default_thank_you.erb
<% first_question = @survey.questions.first
   facebook_url = "https://facebook.com/sharer.php?#{{t: first_question.title, u: @referrer}.to_query}"
   twitter_url = "https://twitter.com/intent/tweet?#{{text: "#{first_question.title} - #{@referrer}"}.to_query}"
%>
<style>
  .polls {
    background-color: rgb(38, 145, 217);
    color: white;
    font-family: roboto-medium;
    font-size: 12px;
    padding: 10px 15px 0 15px;
  }

  .polls div:first-child {
    margin-bottom: 5px;
  }

  .poll {
    text-transform: uppercase;
    line-height: 1;
    margin-bottom: 3px;
    height: 50px;
    width: 100%;
    background-color: rgba(255, 255, 255, 0.2);
    cursor: pointer;
  }

  .poll img {
    width: 50px;
    margin: 0;
    float: left;
    display: inline-block;
  }

  .poll a:hover {
    color: #d1d3d4;
  }

  .poll a {
    font-size: 15px;
    float: right;
    width: 200px;
    font-weight: 500;
    overflow: hidden;
    margin: 0;
    display: inline-block;
    height: 30px;
    padding: 10px 10px 0 5px;
    color: white;
    text-decoration: none;
  }

  .up-menu {
    padding: 10px 5px;
    font-size: 13px;
    font-family: roboto-medium;
    color: #414042;
    font-weight: 100;
    height: 15px;
  }

  .follow-tumblr {
    min-width: 61px;
    min-height: 21px;
  }

  .create-survey {
    float: left;
    text-decoration: none;
    color: #414042;
    margin-left: 10px;
  }

  .up-menu .close-button {
    background-color: #ececec !important;
    color: #414042 !important;
  }

</style>
<div class="up-menu">
  <span style="float: left; margin-right: 4px">Share</span>
  <a class="action-icon tumblr" onclick="openTumblr()"></a>
  <a class="action-icon twitter" onclick="window.open('<%= twitter_url %>', '','width=600,height=400')" target="_blank"></a>
  <a class="action-icon facebook" onclick="window.open('<%= facebook_url %>', '','width=600,height=400')" target="_blank"></a>
  <a class="create-survey" href="<%= ENV['WEB_APP_URL'] %>/#/app/questions/new">Create</a>&nbsp;
  <a href="<%= ENV['WEB_APP_URL'] %>/#/app/questions/new" style="text-decoration: none; margin-right: 10px">
    <img src="<%= asset_path 'ad_units/header-create.png' %>" width="21" height="21"/>
  </a>
  <a href="http://www.tumblr.com/follow/gostatisfy" class="follow-tumblr">
    <img src="<%= asset_path 'ad_units/follow-tumblr.png' %>" width="61" height="21"/>
  </a>
  <a href="<%= qp_start_url(@survey.uuid, @ad_unit.name) %>" target="_self" id="embed-close" class="close-button">x</a>
</div>
<div class="polls">
  <div style="text-align: center">See Related Posts</div>
  <% @sample_surveys.each do |survey| %>
    <% question = survey.questions.first %>
    <div class="poll">
      <img width="50" height="50" src="<%= question.background_image.device_image_url %>"/>
      <a target="_blank" href="<%= survey.referrer %>"><%= question.title %></a>
    </div>
  <% end %>
</div>

app/views/surveys/_embed.html.haml
#embed
  - ad_units = AdUnit.by_name(['medium_rectangle', 'responsive_rectangle']) #AdUnit.all.to_a
  #embed-header
    #embed-title Select Size
    %a#embed-close.close-button x
    %select#embed-select{data: {url: qp_start_url(@survey.uuid, '__ad_unit_name__', subdomain: 'a')}}
      - ad_units.each do |unit|
        %option{value: unit.name, data: unit.as_json(only: [:width, :height, :name])}
          #{unit.name.titleize} (#{unit.width}x#{unit.height})

  %input#embed-input
  :javascript
    var interval = setInterval(function() {
      if (window.jQuery) {
        $('#embed #embed-close').click(function(){
          $('#embed').hide();
        });
        clearInterval(interval)
      }
    }, 50);

app/views/surveys/_footer.html.haml
#footer
  - first_question = @survey.questions.first
  - facebook_url = "https://facebook.com/sharer.php?#{{t: first_question.title, u: @referrer}.to_query}"
  - twitter_url = "https://twitter.com/intent/tweet?#{{text: "#{first_question.title} - #{@referrer}"}.to_query}"

  %a.logo{href: 'http://www.statisfy.co/'}
  - question = @response.present? ? @response.question : @question
  - if question.present?
    %span.answers-count{style: "background-color: #{@survey.theme.color1}"}
      = pluralize question.response_count, 'answer'

  %a.action-icon.tumblr.tooltip{title: 'SHARE ON TUMBLR', onclick: 'openTumblr()'}
  %a.action-icon.twitter.tooltip{title: 'SHARE ON TWITTER', onclick: "window.open('#{twitter_url}', '','width=600,height=400')", target: 'popup'}
  %a.action-icon.facebook.tooltip{title: 'SHARE ON FACEBOOK', onclick: "window.open('#{facebook_url}', '','width=600,height=400')", target: 'popup'}
  %a.action-icon.embed#embed-icon.tooltip{title: 'EMBED', href: '#embed'}
  %a.action-icon.create.tooltip{title: 'CREATE SURVEY', href: "#{ENV['WEB_APP_URL']}/#/app/questions/new"}
:javascript
  function openTumblr() {
    var tumblrOverlay = $('#tumblr-overlay');
    if (tumblrOverlay.css('display') === 'none') {
      tumblrOverlay.css('display', 'initial');
    } else {
      tumblrOverlay.css('display', 'none');
    }
  }

app/views/surveys/_js_config.html.erb
<script type="text/javascript">
  window.adUnitConfig = {
    autoForward: {
      enabled: <%= (Rails.env.production? || Rails.env.labs?).to_json %>,
      speed: <%= settings.fetch(:embeddable_unit_auto_forward, 3).to_i * 1000 %>
    },
    vote: {
      text: "<%= settings.fetch(:embeddable_unit_vote_text, 'Vote Here!').to_s %>",
      duration: <%= settings.fetch(:embeddable_unit_vote_bounce_speed, 1.5).to_f %>
    },
    cta: {
      enabled: <%= (!@response.present?).to_json %>,
      minStart: <%= settings.fetch(:embeddable_unit_cta_min_start, 500).to_i %>,
      maxStart: <%= settings.fetch(:embeddable_unit_cta_max_start, 3000).to_i %>,
      fadeSpeed: <%= settings.fetch(:embeddable_unit_cta_fade_speed, 100).to_i %>,
      duration: <%= settings.fetch(:embeddable_unit_cta_duration, 1000).to_i %>,
      repeat: <%= settings.fetch(:embeddable_unit_cta_repeat, 15000).to_i %>
    },
    feedback: {
      enabled: <%= (!@response.present?).to_json %>,
      duration: <%= settings.fetch(:embeddable_unit_feedback_duration, 300).to_i %>
    },
    responseAnimation: {
      enabled: <%= @response.present?.to_json %>,
      speed: 750
    },
    shareSuggest: {
      text: "<%= settings.fetch(:embeddable_unit_share_suggest_text, 'Share with your friends!').to_s %>",
      duration: "<%= settings.fetch(:embeddable_unit_share_suggest_duration, 1).to_s %>"
    }
  };
</script>

app/views/surveys/_multiple_choice_targeting_script.html.haml
:coffeescript
  interval = setInterval ->
      if window.jQuery
        $(document).ready ->
          scripts = []
          $('[data-targeting-script]').click ->
            script = $(this).data('targeting-script')
            idx = scripts.indexOf(script)
            if idx >= 0
              scripts.splice idx, 1
            else
              scripts.push script

          $('button[type="submit"]').click ->
            scripts.forEach(window.placeTargetingScript)
            scripts.splice 0, scripts.length
        clearInterval(interval)
    , 50

app/views/surveys/_quantcast_js.html.erb
<% content_for :script do %>
  <script type="text/javascript">
    var interval = setInterval(function () {
      if (window.jQuery) {
        var qd = $.Deferred();
        window.qr = function (r) {
          qd.resolve(r.segments)
        };

        $(document).ready(function () {
          var $n = $('#next-button'), qt, click;

          click = function (e) {
            e.preventDefault();
            return false;
          };

          $n.on('click', click);
          qt = setTimeout(function () {
            qd.reject()
          }, 500);
          qd.then(function (d) {
            $.ajax(<%= qp_quantcast_url(@survey.uuid, @ad_unit.name).to_json.html_safe %>, {
              type: 'POST', dataType: 'json', data: {quantcast: JSON.stringify(d)},
              headers: {'X-CSRF-Token': <%= form_authenticity_token.to_json.html_safe %>}
            });
          }).always(function () {
            $n.off('click', click);
            clearTimeout(qt);
          });
          var quantcastCode = "<%= ENV['QUANTCAST_P_CODE'] %>";
          var el = document.createElement('script');
          el.src = "//segapi.quantserve.com/api/segments.json?a=" + quantcastCode + "&callback=qr";
          $(document).append(el);
        });
        clearInterval(interval);
      }
    }, 50);
  </script>

<% end %>

app/views/surveys/_question.html.haml
- question ||= nil
- response ||= nil
- original_referrer ||= nil

#viewed.hidden{data: {url: qp_question_viewed_url(@survey.uuid, @ad_unit.name, @question)}}
:coffee
  interval = setInterval ->
      if window.jQuery
        $ ->
          $.post $("#viewed").data().url
        clearInterval(interval)
    , 50

- content_for :script do
  - if ENV['GOOGLE_ANALYTICS_ID'].present?
    :javascript
      ga('send', 'event', 'embeddable', 'view', '#{@question.id}', 3);

    - if responding?
      :javascript
        ga('send', 'event', 'embeddable', 'response', '#{@question.id}', 3);

= render partial: 'quantcast_js' if response && current_ad_unit_user.quantcast_demographic_required?

:css
  .main-color {
    color: #{@survey.theme.main_color} !important;
  }
  .main-color-bg {
    background-color: #{@survey.theme.main_color} !important;
  }
  .color1 {
    color: #{@survey.theme.color1} !important;
  }
  .color1-bg {
    background-color: #{@survey.theme.color1} !important;
  }
  .color2 {
    color: #{@survey.theme.color2} !important;
  }
  .color2-bg {
    background-color: #{@survey.theme.color2} !important;
  }
= render survey_question_template(@ad_unit.name, question), answer: response, question: question, original_referrer: original_referrer

app/views/surveys/_single_choice_targeting_script.html.haml
:coffeescript
  interval = setInterval ->
      if window.jQuery
        $(document).ready ->
          $('[data-targeting-script]').click ->
            script = $(this).data('targeting-script')
            window.placeTargetingScript(script)
        clearInterval(interval)
    , 50

app/views/surveys/_tumblr.html.haml
- first_question = @survey.questions.first
- tumblr_url = "http://www.tumblr.com/share?v=3&#{{u: @referrer}.to_query}&t=#{(first_question ? first_question.title : '')}"
#tumblr-overlay
  .title
    = image_tag asset_path('embed/tumblr_logo.png'), height: 25, width: 115
  .buttons-container
    %a#open-popup.link-button{href: "javascript:window.open(\"#{tumblr_url}\", '_blank', 'width=400,height=500');void(0);"}
      = image_tag asset_path 'embed/blog-this.png'
      %br
      Blog this
    %a.link-button(href="#{ENV['WEB_APP_URL']}/#/app/questions/new")
      = image_tag asset_path 'embed/create-big.png'
      %br
      Create your
      %br
      own poll

app/views/surveys/question.html.haml
= render "surveys/question", question: @question, response: @response, original_referrer: @original_referrer

app/views/surveys/start.html.haml
- content_for :script do
  :coffee
    interval = setInterval ->
        if window.jQuery
          $ ->
            info = $('#statisfyinfo').data()
            localStorage[info.thankyouUuid] = info.thankyouHtml
            Cookies.set('original_referrer', info.originalReferrer)
          clearInterval(interval)
      , 50

= render "surveys/question", question: @question, response: @response, original_referrer: @original_referrer
.hidden#statisfyinfo{data: {original_referrer: @original_referrer, thankyou: {uuid: @survey.uuid, html: @thank_you_html}}}